kind: pipeline
type: docker
name: gton-capital

pipeline:
  run-test:
    image: node:16
    commands:
      - node --version
      - npm --version
      - npm cache clean --force
      - npm i -d 
      - npm run build
    when:
      event:
        - pull_request

  testnet-deployment:
    image: appleboy/drone-ssh
    host: test.cli.gton.capital
    settings:
      username: root
    key:
      from_secret: ssh_key
    script:
      - cd /var/www/test-terminal/ && sh deploy.sh

    when:
      branch:
        - develop
      event:
        - push

  mainnet-deployment:
    image: appleboy/drone-ssh
    host: cli.gton.capital
    settings:
      username: root
    key:
      from_secret: ssh_key
    script:
      - cd /var/www/terminal-interface/ && sh deploy.sh

    when:
      branch:
        - master
      event:
        - push



trigger:
  branch:
    - drone-integrate
    - master
    - develop
    - testing/current-CI
