kind: pipeline
type: docker
name: gton-capital

pipeline:
  run-test:
    image: node:16.15.1-alpine3.16
    commands:
      - node --version
      - npm --version
      - npm ci
      - npm run build
    when:
      event:
        - pull_request

  testnet-deployment:
    image: appleboy/drone-ssh
    host: cli.gton.capital
    settings:
      username: root
    key:
      from_secret: ssh_key
    script:
      - cd /var/www/test-terminal/ && sh deploy.sh

    when:
      branch:
        - develop
      event:
        - push


trigger:
  branch:
    - drone-integrate
    - develop
