kind: pipeline
type: docker
name: terminal-interface

pipeline:
  run-test:
    image: node
    commands:
      - node --version
      - nvm --version
    when:
      event:
        - pull_request
  deployment:
    image: 12pavelshttp/cli-image
    host: test.cli.gton.capital
    settings:
      username: root
    key:
      from_secret: ssh_key
    port:
      from_secret: ssh_port
    script:
      - cd /var/www/terminal-interface && sh ./.drone/deploy.sh
    when:
      branch:
        - drone-integrate
      event:
        - push

trigger:
  branch:
    - drone-integrate
