kind: pipeline
type: docker
name: terminal-interface

pipeline:
  deployment:
    image: appleboy/drone-ssh
    host: test.cli.gton.capital
    settings:
      username: root
    key:
      from_secret: ssh_key
    port:
      from_secret: ssh_port
    script:
      - cd /var/www/terminal-interface
      - node --version
      - whoami
      - git pull

    when:
      branch:
        - drone-integrate

trigger:
  branch:
    - drone-integrate
