version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run: sudo systemctl unmask docker
      - run: sudo systemctl start docker
      - run: docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
      - run: docker build -t ${CONTAINER_TAG} . && docker push ${CONTAINER_TAG}
      # Whatever you want to do
      - run: sudo apt-get update && sudo apt-get install -y kubectl
      - run: kubectl config set-cluster cluster-name --server=${CLUSTER_URL} --insecure-skip-tls-verify=true
      - run: kubectl config set-context context-name --cluster=cluster-name
      - run: kubectl config set-credentials ${USER} --token=${TOKEN}
      - run: kubectl config set-context context-name --user=${USER}
      - run: kubectl config set-context context-name --namespace=${NAMESPACE}
      - run: kubectl config use-context context-name
      - run: kubectl rollout restart deployment ${DEPLOYMENT}