version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y kubectl docker
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
      - run: docker build -t ${CONTAINER_TAG} . && docker push ${CONTAINER_TAG}
      # Whatever you want to do
      - run: echo ${CUBE_CONFIG} >> config.yaml
      - run: kubectl --kubeconfig=config.yaml rollout restart deployment ${DEPLOYMENT} --namespace=${NAMESPACE}