version: 2.0
orbs:
  aws-eks: circleci/aws-eks@2.1.0
  kubernetes: circleci/kubernetes@1.0
jobs:
  docker-image-build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
      - run: docker build -t ${CONTAINER_TAG} . && docker push ${CONTAINER_TAG}
  cluster-deploy:
    #executor: aws-eks/python3
    docker:
      - image: cimg/python:3.8
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: ${CLUSTER_NAME}
      - run: kubectl rollout restart deployment ${DEPLOYMENT} --namespace=${NAMESPACE}     
workflows:
  version: 2
  build-deploy:
    jobs:
     # - dockerImageBuild
      - cluster-deploy
